export default {
	LAYOUT: {
		COMPONENTS: {
			HEADER: {
				AUTH_FORM_TYPE: 'form',
				REGISTER_BUTTON: true,
				SOCIAL_BUTTONS: false,
				LANGUAGE_SWITCHER: true,
				MENU_INTEGRATED: false,
				REGISTER_BUTTON_MOBILE: true,
				MOBILE_HEADER_BALANCE: true
			},
			GAME_LIST: {
				FILTER: { ICON_POSITION: 'top' },
				ITEM: { STYLE: 'full', SHOW_PROVIDER: false }
			},
			REGISTER: { HAS_CONTAINER: true, FORM_ALIGNMENT: 'center', SOCIAL_SERVICES_POSITION: 'none' },
			PROFILE: {
				USER_MENU_POSITION: 'top',
				TRANSACTION_HISTORY: { FILTER_TYPE: 'dropdown' },
				PAYMENTS_LIST_OPENED: 'false'
			}
		},
		COMMON: { INPUT: { LABEL: 'top' } },
		POPUPS: { LOGIN: { AUTH_FORM: true, REGISTER_BUTTON: true, SOCIAL_SERVICES_POSITION: 'none' } },
		IMAGE_SIZES: {
			DESKTOP: {
				BLOCK_SLIDER_WIDTH_BOTH: 960,
				BLOCK_SLIDER_HEIGHT_BOTH: 386,
				FLUID_SLIDER_WIDTH_SERVER: 1920,
				FLUID_SLIDER_WIDTH_BROWSER: '100%',
				FLUID_SLIDER_HEIGHT_BOTH: 386,
				FULL_SLIDER_WIDTH_SERVER: 1920,
				FULL_SLIDER_WIDTH_BROWSER: '100%',
				REGULAR_GAME_ITEM_WIDTH_BOTH: 232,
				REGULAR_GAME_ITEM_HEIGHT_BOTH: 172,
				LARGE_GAME_ITEM_WIDTH_BOTH: 474,
				LARGE_GAME_ITEM_HEIGHT_BOTH: 354,
				SQUARE_GAME_ITEM_WIDTH_BOTH: 474,
				SQUARE_GAME_ITEM_HEIGHT_BOTH: 354,
				HORIZONTAL_GAME_ITEM_WIDTH_BOTH: 474,
				HORIZONTAL_GAME_ITEM_HEIGHT_BOTH: 172,
				VERTICAL_GAME_ITEM_WIDTH_BOTH: 232,
				VERTICAL_GAME_ITEM_HEIGHT_BOTH: 354,
				ANY_LOGO_WIDTH_BOTH: 238,
				ANY_LOGO_HEIGHT_BOTH: 53,
				ANY_FOOTER_IMAGE_HEIGHT_BOTH: 30,
				ANY_BACKGROUND_WIDTH_SERVER: 1920,
				ANY_BACKGROUND_WIDTH_BROWSER: '100%',
				CARD_PROMOTION_WIDTH_BOTH: 320,
				CARD_PROMOTION_HEIGHT_BOTH: 194,
				DEFAULT_PROMOTION_WIDTH_BOTH: 610,
				DEFAULT_PROMOTION_HEIGHT_BOTH: 281
			},
			MOBILE: {
				BLOCK_SLIDER_WIDTH_SERVER: 414,
				BLOCK_SLIDER_WIDTH_BROWSER: '100%',
				FLUID_SLIDER_WIDTH_SERVER: 414,
				FLUID_SLIDER_WIDTH_BROWSER: '100%',
				FULL_SLIDER_WIDTH_SERVER: 414,
				FULL_SLIDER_WIDTH_BROWSER: '100%',
				REGULAR_GAME_ITEM_WIDTH_BOTH: 232,
				REGULAR_GAME_ITEM_HEIGHT_BOTH: 172,
				LARGE_GAME_ITEM_WIDTH_BOTH: 474,
				LARGE_GAME_ITEM_HEIGHT_BOTH: 354,
				SQUARE_GAME_ITEM_WIDTH_BOTH: 474,
				SQUARE_GAME_ITEM_HEIGHT_BOTH: 354,
				HORIZONTAL_GAME_ITEM_WIDTH_BOTH: 474,
				HORIZONTAL_GAME_ITEM_HEIGHT_BOTH: 172,
				VERTICAL_GAME_ITEM_WIDTH_BOTH: 232,
				VERTICAL_GAME_ITEM_HEIGHT_BOTH: 354,
				ANY_LOGO_WIDTH_BOTH: 198,
				ANY_LOGO_HEIGHT_BOTH: 44,
				ANY_FOOTER_IMAGE_HEIGHT_BOTH: 24,
				ANY_BACKGROUND_WIDTH_SERVER: 414,
				ANY_BACKGROUND_WIDTH_BROWSER: '100%',
				CARD_PROMOTION_WIDTH_BOTH: 352,
				CARD_PROMOTION_HEIGHT_BOTH: 214,
				DEFAULT_PROMOTION_WIDTH_BOTH: 374,
				DEFAULT_PROMOTION_HEIGHT_BOTH: 247
			}
		}
	},
	APP: { NAME: 'Singular DEV', URL: 'https://newsite.singulardev.uk' },
	SEO: {
		DEFAULT_TITLE: 'The most diverse and fun gaming site to play at.',
		DEFAULT_DESCRIPTION: 'The most diverse and fun gaming site to play at. (Description)',
		DEFAULT_HEADING: 'The most diverse and fun gaming site to play at. (About)',
		DEFAULT_KEYWORDS: 'casino,betting,gaming,gambling',
		DEFAULT_IMAGE: 'https://newstatic.singulardev.uk/website/fb_broken.jpg'
	},
	I18N: {
		AVAILABLE_LANGUAGES: [
			{ code: 'ka', culture: 'ge-ka', name: 'Georgian', alpha_2_code: 'GE' },
			{ code: 'ru', culture: 'ru-ru', name: 'Russian', alpha_2_code: 'RU' },
			{ code: 'en', culture: 'en-en', name: 'English', alpha_2_code: 'EN' },
			{ code: 'fr', culture: 'fr-fr', name: 'French', alpha_2_code: 'FR' }
		],
		DEFAULT_LANGUAGE: { code: 'en', culture: 'en-en', name: 'English', alpha_2_code: 'EN' }
	},
	DEFAULT_CURRENCY_ID: 3,
	SUPPORTED_CURRENCIES: [
		26,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		15,
		99,
		98,
		95,
		96,
		16,
		1,
		17,
		18,
		19,
		20,
		21,
		22,
		23,
		24,
		25,
		100
	],
	CURRENCIES: {
		DATA: {
			1: 'KZT',
			2: 'GEL',
			3: 'USD',
			4: 'EUR',
			5: 'GBP',
			6: 'RUB',
			7: 'UAH',
			8: 'AMD',
			9: 'NGN',
			11: 'TMT',
			12: 'TLR',
			15: 'THB',
			16: 'GHS',
			17: 'BYN',
			18: 'MGA',
			19: 'KES',
			20: 'ZAR',
			21: 'RWF',
			22: 'TZS',
			23: 'UGX',
			24: 'MYR',
			25: 'MKD',
			26: 'HUF',
			95: 'mBTC',
			96: 'uBTC',
			99: 'BTC'
		},
		PARAMS: {
			KZT: { symbol: '\u20b8', position: 'start', separated: true },
			GEL: { symbol: '\u20be', position: 'end', separated: true },
			USD: { symbol: '$', position: 'start', separated: false },
			EUR: { symbol: '\u20ac', position: 'start', separated: false },
			GBP: { symbol: '\u00a3', position: 'start', separated: false },
			RUB: { symbol: '\u20bd', position: 'end', separated: false },
			UAH: { symbol: '\u20b4', position: 'start', separated: true },
			AMD: { symbol: '\u058f', position: 'end', separated: false },
			NGN: { symbol: '\u20a6', position: 'start', separated: false },
			TMT: { symbol: 'TMT', position: 'end', separated: true },
			TLR: { symbol: '\u20ba', position: 'start', separated: false },
			THB: { symbol: '\u0e3f', position: 'start', separated: false },
			GHS: { symbol: 'GH\u20b5', position: 'start', separated: false },
			BYN: { symbol: 'Br', position: 'end', separated: true },
			MGA: { symbol: 'Ar', position: 'start', separated: true },
			KES: { symbol: 'KSh', position: 'start', separated: false },
			ZAR: { symbol: 'R', position: 'start', separated: false },
			RWF: { symbol: 'FRw', position: 'start', separated: false },
			TZS: { symbol: 'TSh', position: 'start', separated: false },
			UGX: { symbol: 'UGX', position: 'start', separated: false },
			MYR: { symbol: 'RM', position: 'start', separated: false },
			mBTC: { symbol: 'mBTC', position: 'end', separated: true },
			uBTC: { symbol: '\u03bcBTC', position: 'end', separated: true },
			BTC: { symbol: '\u20bf', position: 'start', separated: false },
			MKD: { symbol: '\u0434\u0435\u043d', position: 'start', separated: false },
			HUF: { symbol: 'Ft', position: 'end', separated: true }
		},
		SUPPORTED: [6, 7, 16, 17, 2, 1, 26]
	},
	DEFAULT_COUNTRY_ID: 268,
	DEFAULT_COUNTRY_DIAL_IN: null,
	REDIRECT_BY_COUNTRY: [],
	SUPPORTED_CHANNELS: [1, 2, 4],
	SUPPORTED_DOCUMENT_TYPES: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
	SUPPORTED_TRANSACTION_TYPES: ['', 0, 1],
	DEFAULT_STATUS_ID: 13,
	MOBILE_HEADER_BALANCE: true,
	CORE_STATUSES: {
		0: 'Test User',
		1: 'Registered',
		2: 'Verified',
		3: 'Full Block',
		4: 'Game Block',
		5: 'Withdraw Blocked',
		6: 'VIP',
		7: 'Verified 50',
		8: 'Verified 100',
		9: 'Verified 125',
		10: 'Verified 150',
		11: 'Verified 200',
		12: 'test_status_1',
		13: 'test_status_2',
		21: 'Regulatory Excluded',
		22: 'Regulatory Suspicious',
		99: 'Temp Block',
		100: 'LAZARE_STATUS',
		103: 'WARRIOR_TESTER',
		106: 'WARRIOR_TESTER',
		109: 'WARRIOR_TESTER',
		112: 'WARRIOR_TESTER',
		115: 'WARRIOR_TESTER',
		118: 'WARRIOR_TESTER',
		121: 'WARRIOR_TESTER',
		124: 'WARRIOR_TESTER',
		127: 'WARRIOR_TESTER',
		130: 'WARRIOR_TESTER',
		133: 'WARRIOR_TESTER'
	},
	CORE_DOCUMENT: {
		TYPES: {
			1: 'ID_CARD',
			2: 'PASSPORT',
			3: 'HOME_REGISTRY',
			4: 'DRIVING_LICENSE',
			5: 'WARRANT',
			6: 'FACE_ID',
			7: 'OTHER_ID',
			8: 'PROOF_OF_ADDRESS',
			9: 'BANK_STATEMENT',
			10: 'SCAN_OF_CARD',
			11: 'SCREENSHOT_OF_EWALLET',
			12: 'SOURCE_OF_FUNDS',
			13: 'OTHER_DOCUMENTS',
			14: 'BANK_ACCOUNT_ID',
			15: 'TEST_TYPE'
		},
		FIELDS: {
			ID_CARD: { HAS_ID: true, HAS_NUMBER: false },
			PASSPORT: { HAS_ID: true, HAS_NUMBER: true },
			HOME_REGISTRY: { HAS_ID: false, HAS_NUMBER: true },
			DRIVING_LICENSE: { HAS_ID: false, HAS_NUMBER: true },
			WARRANT: { HAS_ID: false, HAS_NUMBER: true },
			FACE_ID: { HAS_ID: true, HAS_NUMBER: false },
			OTHER_ID: { HAS_ID: true, HAS_NUMBER: false },
			PROOF_OF_ADDRESS: { HAS_ID: false, HAS_NUMBER: true },
			BANK_STATEMENT: { HAS_ID: false, HAS_NUMBER: true },
			SCAN_OF_CARD: { HAS_ID: false, HAS_NUMBER: true },
			SCREENSHOT_OF_EWALLET: { HAS_ID: false, HAS_NUMBER: true },
			SOURCE_OF_FUNDS: { HAS_ID: false, HAS_NUMBER: true },
			OTHER_DOCUMENTS: { HAS_ID: false, HAS_NUMBER: true },
			BANK_ACCOUNT_ID: { HAS_ID: true, HAS_NUMBER: true, INPUT_LABEL: 'BANK_ACCOUNT_ID' }
		},
		UPLOAD_FORM: {
			DEFAULT: {
				IMAGES: [
					{ LABEL: 'DOCUMENT_FRONT', TYPE: 'SCAN' },
					{ LABEL: 'DOCUMENT_BACK', TYPE: 'SCAN' }
				]
			},
			PASSPORT: {
				IMAGES: [
					{ LABEL: 'PAGE_31', TYPE: 'SCAN' },
					{ LABEL: 'PAGE_32_33', TYPE: 'SCAN' },
					{ LABEL: 'PAGE_WITH_THE_LAST_REGISTRATION_ADDRESS', TYPE: 'SCAN' },
					{ LABEL: 'SELFIE_WITH_PASSPORT_PAGE_32_33', TYPE: 'LIVENESS' }
				]
			},
			RESIDENCE_PERMIT: {
				IMAGES: [
					{ LABEL: 'PAGE_15', TYPE: 'SCAN' },
					{ LABEL: 'PAGE_16_17', TYPE: 'SCAN' },
					{ LABEL: 'PAGE_WITH_THE_LAST_REGISTRATION_ADDRESS', TYPE: 'SCAN' },
					{ LABEL: 'SELFIE_WITH_PASSPORT_PAGE_16_17', TYPE: 'LIVENESS' }
				]
			}
		},
		DEFAULT: { DOCUMENT_TYPE: '1' }
	},
	DOCUMENT_ISSUING_AUTHORITIES: { 7: ['Public Service Hall', 'Other'], 16: [] },
	DOCUMENT_ISSUING_AUTHORITY_IN_NEW_DOCUMENT: true,
	DOCUMENT_ISSUING_PLACE_IN_NEW_DOCUMENT: true,
	DOCUMENT_ISSUE_DATE_IN_NEW_DOCUMENT: true,
	ENDPOINTS: {
		STATIC: 'https://newstatic.singulardev.uk/website',
		PAYMENTS_SDK: 'https://newstatic.singulardev.uk/payments-sdk',
		SIS: 'https://siswebapi.singulardev.uk/api/v1/init',
		CANON: 'https://mediaproxy.singulardev.uk',
		BACKOFFICE: 'https://backoffice.singulardev.uk',
		JACKPOT: 'https://jackpot.singulardev.uk',
		SIS_GAMES: 'https://sisgames.singulardev.uk',
		BASE: 'https://singulardev.uk',
		API: 'https://websiteapi.singulardev.uk',
		API_SERVICE: 'https://websiteapiv2:8080',
		SPORTSBOOK: 'https://sports.singularqa.uk',
		CORE_API: 'https://coreapi.singulardev.uk',
		AUTH_PROXY: 'https://authproxy.singulardev.uk',
		TEST_ENDPINT: 'https://test.endpoint.test',
		SAM: 'https://sam.singulardev.uk',
		SBO_API: 'https://backofficeapi.singulardev.uk',
		UBO_API: 'https://ubo-api.singulardev.uk',
		SIS_PAYMENTS: 'https://sispay.singulardev.uk',
		WEB_SITE_DOMAIN: 'https://singulardev.uk',
		IMAGE_HOST: 'https://https://backoffice.singulardev.uk',
		IMAGE_STATIC_URL: 'https://https://newstatic.singulardev.uk',
		AGENTS_API: 'https://https://retailapi.singulardev.uk/',
		GAME_DIRECTORY_MANAGER: 'https://https://gamedirectory.singulardev.uk'
	},
	REGISTRATION: {
		KYC_POPUP: true,
		KYC_STEPS: [
			{ label: 'MOBILE_NUMBER', visible: true },
			{ label: 'EMAIL_ADDRESS', visible: true },
			{
				label: 'PERSONAL_DETAILS',
				visible: true,
				fields: {
					Name: true,
					Surname: true,
					MaidenName: true,
					MotherMaidenName: true,
					PlaceOfBirth: true,
					Gender: true
				}
			},
			{
				label: 'ADDRESS',
				visible: true,
				fields: {
					AddressLine1: true,
					AddressLine2: false,
					AddressLine3: false,
					Town: true,
					County: false,
					Region: true,
					PostCode: true
				}
			},
			{
				label: 'DOCUMENTS',
				visible: true,
				fields: {
					DocumentCountryID: false,
					DocumentIssueDate: true,
					DocumentExpirationDate: true,
					DocumentIssuingPlace: false,
					DocumentIssuingAuthority: true
				}
			}
		]
	},
	PAYMENT_SDK: { DEPOSIT_URL: null, PROVIDER_ID: null, WITHDRAW_URL: null },
	USER_CAN_CHANGE_CURRENCY: true,
	HAS_PICTURE_IN_PICTURE_MODE: true,
	HAS_RESPONSIBLE_GAMBLING: true,
	LIMIT_CANCELLATION_TIME: 90,
	SERVICES: {
		RPG: '3dc89bbf-ff3f-49bd-a346-ece5bb590af3',
		UFG: '18ae9931-fa38-478b-9220-84653bb9f99a',
		CBS: '11e91f20-11f2-3010-9d75-00505685245f',
		DOC: '11e901fc-4b30-1720-a76c-000c2976934b',
		SIS: '11e844a5-1c28-83f0-8768-000c29034530',
		PAY: '11e91f20-11f2-3010-9d75-00505685245f'
	},
	THEMES: {
		LIST: ['light', 'dark'],
		DEFAULT: 'dark',
		COLORS: { light: '#f0f0f0', dark: '#101010' },
		PALETTE: 'singular'
	},
	THEME_LIST: ['light', 'dark'],
	DEFAULT_THEME: 'dark',
	DEFAULT_PALETTE: 'singular',
	EXTERNAL_SERVICES: null,
	SUPPORT_EMAIL: 'support@singulardev.uk',
	GAME: { OPEN_STRATEGY: 'page', POPUP_WIDTH: 990, POPUP_HEIGHT: 660 },
	HAS_DEMO_PLAY: true,
	HAS_COOKIE_BANNER: false,
	PASSWORD_EXPIRATION_DAYS: 30,
	SESSION_EXPIRATION_TIME: 900,
	HAS_WELCOME_PAGE: false,
	LIMIT_ACTIVATION_TIME: 24,
	LIMIT_CANCELATION_TIME: 24,
	SELF_SUSPEND_TIMES: [24, 168, 720],
	ACTIVITY_CHECK_TIMES: [5, 30, 60],
	ACTIVITY_CHECK_DIFF_TIME: 10,
	SESSION_LIMITATION_TIMES: [30, 60, 120],
	LIMITS: {
		HAS_RESPONSIBLE_GAMBLING: true,
		HAS_FINANCIAL_LIMITS: true,
		HAS_DEPOSIT_LIMIT: true,
		HAS_WAGER_LIMIT: true,
		HAS_LOSS_LIMIT: true,
		HAS_SELF_EXCLUSION: true,
		HAS_SELF_SUSPEND: true,
		HAS_ACTIVITY_CHECK: true,
		HAS_SESSION_LIMITATION: true,
		DEPOSIT_LIMIT_RANGE: [0, 100],
		WAGER_LIMIT_RANGE: [0, 50],
		LOSS_LIMIT_RANGE: [0, 25],
		LIMIT_ACTIVATION_TIME: 24,
		LIMIT_CANCELATION_TIME: 24,
		SELF_SUSPEND_TIMES: [24, 168, 720],
		ACTIVITY_CHECK_TIMES: [60],
		ACTIVITY_CHECK_DIFF_TIME: 10,
		SESSION_LIMITATION_TIMES: [30, 60, 120],
		SINGLE_ACTIVITY_CHECK_TIME: 60
	},
	ACTIVE_FINANCIAL_LIMIT_ALLOWANCE_INCREASE_NOT_ALLOWED: false,
	ACTIVE_SESSION_LIMIT_ALLOWANCE_INCREASE_NOT_ALLOWED: false
};
